-- ============================================================
-- 3D TECH E-Commerce Admin Dashboard - Supabase Schema
-- ============================================================

-- ============================================================
-- ORDERS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT UNIQUE NOT NULL,
    customer_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    governorate TEXT NOT NULL,
    city TEXT NOT NULL,
    address_details TEXT,
    
    -- Items info
    product_names TEXT NOT NULL,
    total NUMERIC NOT NULL,
    
    -- Payment info
    payment_method TEXT NOT NULL,
    payment_status TEXT DEFAULT 'pending',
    receipt_url TEXT,
    
    -- Shipping info
    shipping_method TEXT NOT NULL,
    order_status TEXT DEFAULT 'new',
    
    -- Notes
    notes TEXT,
    customer_notes TEXT,
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read orders" ON public.orders;
DROP POLICY IF EXISTS "Allow public insert orders" ON public.orders;
DROP POLICY IF EXISTS "Allow public update orders" ON public.orders;
CREATE POLICY "Allow public full access" ON public.orders FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_customer_name ON public.orders(customer_name);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON public.orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_order_status ON public.orders(order_status);

-- ============================================================
-- ORDER ITEMS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id),
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC NOT NULL,
    total_price NUMERIC NOT NULL,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public access to order items" ON public.order_items;
CREATE POLICY "Allow public full access" ON public.order_items FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);

-- ============================================================
-- CUSTOMERS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL UNIQUE,
    email TEXT,
    governorate TEXT,
    city TEXT,
    
    -- Stats
    total_orders INTEGER DEFAULT 0,
    total_spent NUMERIC DEFAULT 0,
    last_order_date TIMESTAMP WITH TIME ZONE,
    
    -- Metadata
    notes TEXT,
    is_blocked BOOLEAN DEFAULT false,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public access to customers" ON public.customers;
CREATE POLICY "Allow public full access" ON public.customers FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_customers_phone ON public.customers(phone);
CREATE INDEX IF NOT EXISTS idx_customers_created_at ON public.customers(created_at DESC);

-- ============================================================
-- DISCOUNT CODES TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.discount_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    discount_type TEXT NOT NULL,
    discount_value NUMERIC NOT NULL,
    
    -- Limits
    min_order NUMERIC,
    max_uses INTEGER,
    used_count INTEGER DEFAULT 0,
    
    -- Date range
    starts_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT true,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.discount_codes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public access to discount codes" ON public.discount_codes;
CREATE POLICY "Allow public full access" ON public.discount_codes FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_discount_codes_code ON public.discount_codes(code);
CREATE INDEX IF NOT EXISTS idx_discount_codes_is_active ON public.discount_codes(is_active);

-- Function to increment coupon used count
CREATE OR REPLACE FUNCTION increment_coupon_used_count(coupon_id BIGINT)
RETURNS void
LANGUAGE SQL
SECURITY DEFINER
AS $$
  UPDATE public.discount_codes SET used_count = used_count + 1 WHERE id = coupon_id;
$$;

-- ============================================================
-- SHIPPING METHODS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.shipping_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    label_ar TEXT NOT NULL,
    price NUMERIC NOT NULL,
    duration TEXT,
    
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.shipping_methods ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public access to shipping methods" ON public.shipping_methods;
CREATE POLICY "Allow public full access" ON public.shipping_methods FOR ALL USING (true) WITH CHECK (true);

-- Insert default shipping methods
DELETE FROM public.shipping_methods;
INSERT INTO public.shipping_methods (key, label, label_ar, price, duration, is_active, sort_order) VALUES
    ('office', 'Office Delivery', 'توصيل للمكتب', 1.000, '2-4 أيام عمل', true, 1),
    ('home', 'Home Delivery', 'توصيل للمنزل', 2.000, '2-4 أيام عمل', true, 2),
    ('pickup', 'Store Pickup', 'استلام من المتجر', 0.000, 'فوري', true, 3)
ON CONFLICT DO NOTHING;

-- ============================================================
-- PAYMENT SETTINGS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.payment_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Bank transfer settings
    bank_transfer_enabled BOOLEAN DEFAULT true,
    bank_account_name TEXT,
    bank_account_number TEXT,
    bank_transfer_number TEXT,
    bank_name TEXT,
    bank_payment_instructions TEXT,
    bank_logo_url TEXT,
    
    -- Cash on delivery settings
    cash_on_delivery_enabled BOOLEAN DEFAULT true,
    cod_deposit_amount NUMERIC DEFAULT 5.000,
    cod_deposit_instructions TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.payment_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public access to payment settings" ON public.payment_settings;
CREATE POLICY "Allow public full access" ON public.payment_settings FOR ALL USING (true) WITH CHECK (true);

-- Insert default payment settings
DELETE FROM public.payment_settings;
INSERT INTO public.payment_settings (
    bank_transfer_enabled,
    bank_account_name,
    bank_account_number,
    bank_transfer_number,
    bank_name,
    cash_on_delivery_enabled,
    cod_deposit_amount
) VALUES (
    true,
    '3D TECH Store',
    '00000000000000',
    '000000000',
    'Bank Name',
    true,
    5.000
);

-- ============================================================
-- SITE SETTINGS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.site_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL,
    value_type TEXT DEFAULT 'text',
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public access to site settings" ON public.site_settings;
CREATE POLICY "Allow public full access" ON public.site_settings FOR ALL USING (true) WITH CHECK (true);

-- Insert default site settings
DELETE FROM public.site_settings;
INSERT INTO public.site_settings (key, value, value_type) VALUES
    ('store_name_ar', '3D TECH', 'text'),
    ('store_name_en', '3D TECH', 'text'),
    ('store_logo_url', '/logo.png', 'url'),
    ('splash_screen_logo_url', '/logo.png', 'url'),
    ('whatsapp_number', '96894353535', 'text'),
    ('instagram_url', 'https://instagram.com', 'url'),
    ('email', 'info@3dtech.store', 'text'),
    ('address', 'Muscat, Oman', 'text'),
    ('primary_color', '#16B8BE', 'color'),
    ('header_color', '#10292D', 'color'),
    ('footer_color', '#10292D', 'color'),
    ('hero_title_ar', 'نطبع أفكارك ب��بداع', 'text'),
    ('hero_title_en', 'We Print Your Ideas', 'text'),
    ('hero_subtitle_ar', '', 'text'),
    ('hero_subtitle_en', '', 'text'),
    ('hero_cta_text', 'Shop Now', 'text'),
    ('hero_cta_link', 'shop', 'text'),
    ('splash_screen_enabled', 'true', 'boolean'),
    ('splash_screen_duration', '900', 'number'),
    ('animated_dots_enabled', 'true', 'boolean'),
    ('shipping_message', 'Fast and secure delivery to all regions', 'text'),
    ('payment_message', 'Secure payment options available', 'text')
ON CONFLICT DO NOTHING;

-- ============================================================
-- ADMIN USERS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.admin_users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    role TEXT DEFAULT 'admin',
    is_active BOOLEAN DEFAULT true,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public access to admin users" ON public.admin_users;
CREATE POLICY "Allow public full access" ON public.admin_users FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_admin_users_email ON public.admin_users(email);

-- ============================================================
-- Triggers for updated_at
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS orders_updated_at ON public.orders;
CREATE TRIGGER orders_updated_at BEFORE UPDATE ON public.orders
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS discount_codes_updated_at ON public.discount_codes;
CREATE TRIGGER discount_codes_updated_at BEFORE UPDATE ON public.discount_codes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS shipping_methods_updated_at ON public.shipping_methods;
CREATE TRIGGER shipping_methods_updated_at BEFORE UPDATE ON public.shipping_methods
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS payment_settings_updated_at ON public.payment_settings;
CREATE TRIGGER payment_settings_updated_at BEFORE UPDATE ON public.payment_settings
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS site_settings_updated_at ON public.site_settings;
CREATE TRIGGER site_settings_updated_at BEFORE UPDATE ON public.site_settings
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS customers_updated_at ON public.customers;
CREATE TRIGGER customers_updated_at BEFORE UPDATE ON public.customers
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS admin_users_updated_at ON public.admin_users;
CREATE TRIGGER admin_users_updated_at BEFORE UPDATE ON public.admin_users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
